let x;
const num = new Number(5);
x = num.toString();
x = num.toString().length;
x = num.toFixed(2);
x = num.toPrecision(4);
x = num.toExponential(2);
x = num.toLocaleString('en-US');
x = num.valueOf();
x = Number.MAX_VALUE;
x = Number.MIN_VALUE;
console.log(x);