let x;
x = 5 + '5';
x = 5 + Number('5');
x = 5 * '5';
x = 5 + null;
x = 5 + Number(null);
x = 5 + Number(true);
x = 5 + Number(false);
x = 5 + false;
x = 5 + true;
x = 5 + undefined;
console.log(x, typeof x);